mysite/cart/urls.py
from django.urls import path

from .views import cart_add, cart_change, cart_remove

app_name = 'cart'

urlpatterns = [
    path('cart-add/', cart_add, name='cart_add'),
    path('cart-change/', cart_change, name='cart_change'),
    path('cart-remove/', cart_remove, name='cart_remove'),
]

mysite/goods/urls.py
from django.urls import path

from .views import (CategoryListView,
                    ProductDetailsView)
app_name = 'goods'

urlpatterns = [
    path('search/', CategoryListView.as_view(), name='search'),
    path('<slug:category_slug>/', CategoryListView.as_view(), name='index'),
    path('product/<int:pk>/', ProductDetailsView.as_view(), name='product')
]

mysite/main/urls.py
from django.urls import path

from .views import (index,
                    about)
app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about')
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='goods')),
    path('user/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/order/urls.py
from django.urls import path
from .views import create_order, OrderListView

app_name = 'order'


urlpatterns = [
    path('create-order/', create_order, name='create_order'),
    path('order-list/', OrderListView.as_view(), name='order_list'),
]

mysite/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from .views import (login,
                    registration,
                    UserProfileView,
                    user_logout,
                    user_cart,
                    UserPasswordChangeView,
                    UserPasswordResetView,
                    UserPasswordResetDoneView,
                    UserPasswordResetConfirmView
                    )

app_name = 'users'


urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('user-cart/', user_cart, name='user-cart'),
    path('logout/', user_logout, name='logout'),
    path('password-change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('reset-password/', UserPasswordResetView.as_view(), name='password_reset'),
    path('reset-password-done/', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]

mysite/templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href='{% static "deps/css/bootstrap/bootstrap.min.css" %}'>
    <link rel="stylesheet" href='{% static "deps/css/my_css.css" %}'>
    <!-- Стиль footer-a для главной страницы -->
    {% block css %}
    {% endblock %}
    <!-- Favicons for different platforms -->
    <link rel="apple-touch-icon" sizes="180x180" href='{% static "deps/favicon/apple-touch-icon.png" %}'>
    <link rel="icon" type="image/png" sizes="32x32" href='{% static "deps/favicon/favicon-32x32.png" %}'>
    <link rel="icon" type="image/png" sizes="16x16" href='{% static "deps/favicon/favicon-16x16.png" %}'>
    <link rel="manifest" href='{% static "deps/favicon/site.webmanifest" %}'>
    <title>{{ title }}</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'main:index' %}">RegalRidge</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Information
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item  text-white" href="{% url 'order:order_list' %}">Shipping and payment</a></li>
                                <li><a class="dropdown-item  text-white" href="#">Contact Information</a></li>
                                <li><a class="dropdown-item  text-white" href="{% url 'main:about' %}">About Us </a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  text-white" href="{% url 'users:user-cart' %}">Basket</a>
                        </li>

                        {% if request.user.is_authenticated %}
                            <li class="nav-item dropdown ">
                                <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                    My profile
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item  text-white" href="{% url 'users:profile' %}">Personal area</a>
                                    </li>
                                    {% if request.user.is_admin or request.user.is_staff %}
                                        <li><a class="dropdown-item  text-white" href="{% url 'admin:index' %}">Admin panel</a></li>
                                    {% endif %}
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item  text-white" href="{% url 'users:logout' %}">Log out</a></li>
                                </ul>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link  text-white" href="{% url 'users:login' %}">Log in</a>
                            </li>
                        {% endif %}

                    </ul>
                    <form class="d-flex" role="search" action="{% url 'goods:search' %}" method="get">
                        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success text-white" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <section>
        <div class="container">
            <!-- Каталог и корзина с фиксированным расположением на странице -->
            <div class="row mt-1 position-fixed z-3">
                <!-- Каталог -->
                <div class="dropdown mb-2">
                    <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Catalog
                        <img class="mx-1" src='{% static "deps/icons/grid-fill.svg" %}' alt="Catalog Icon" width="16"
                            height="16">
                    </button>
                    <ul class="dropdown-menu bg-dark" data-bs-theme="dark">
                        {% for category in categories %}
                            <li><a class="dropdown-item text-white" href="{% url 'goods:index' category.slug %}">{{ category.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <!-- Значек корзины, вызывает модальное окно -->
                {% block model_cart %} {% endblock %}
                <!-- Закончилась разметка модального окна -->
            </div>
        </div>
        <!-- Контент -->
        <div class="container">
            <div class="row mt-1">
                <div class="col-lg-2">
                    <!-- Пустой блок на Ваше усмотрение -->
                </div>
                <div class="col-lg-10">
                    <!-- Контент на странице -->
                    {% include "includes/notifications.html" %}
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </section>
    {% block footer %}
    {% endblock %}
    <script src='{% static "deps/js/jquery/jquery-3.7.0.min.js" %}'></script>
    <script src='{% static "deps/js/jquery-ajax.js" %}'></script>
    <script src='{% static "deps/js/bootstrap/bootstrap.bundle.min.js" %}'></script>
</body>

</html>