mysite/cart/urls.py
from django.urls import path

from .views import cart_add, cart_change, cart_remove

app_name = 'cart'

urlpatterns = [
    path('cart-add/', cart_add, name='cart_add'),
    path('cart-change/', cart_change, name='cart_change'),
    path('cart-remove/', cart_remove, name='cart_remove'),
]

mysite/goods/urls.py
from django.urls import path

from .views import (CategoryListView,
                    ProductDetailsView)
app_name = 'goods'

urlpatterns = [
    path('search/', CategoryListView.as_view(), name='search'),
    path('<slug:category_slug>/', CategoryListView.as_view(), name='index'),
    path('product/<int:pk>/', ProductDetailsView.as_view(), name='product')
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='goods')),
    path('user/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/order/urls.py
from django.urls import path
from .views import create_order, OrderListView

app_name = 'order'


urlpatterns = [
    path('create-order/', create_order, name='create_order'),
    path('order-list/', OrderListView.as_view(), name='order_list'),
]

mysite/order/models.py
from users.models import User
from django.db import models
from goods.models import Products

class OrderItemQueryset(models.QuerySet):
    def total_price(self):
        return sum(cart.products_price() for cart in self)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        else:
            return 0

class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, verbose_name="Пользователь", default=None)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания заказа")
    phone_number = models.CharField(max_length=20, verbose_name="Номер телефона")
    requires_delivery = models.BooleanField(default=False, verbose_name="Требуется доставка")
    delivery_address = models.TextField(null=True, blank=True, verbose_name="Адрес доставки")
    payment_on_get = models.BooleanField(default=False, verbose_name="Оплата при получении")
    is_paid = models.BooleanField(default=False, verbose_name="Оплачено")
    status = models.CharField(max_length=50, default='В обработке', verbose_name="Статус заказа")

    class Meta:
        db_table = 'order'

    def __str__(self):
        return f"Order № {self.pk} | Buyer {self.user.first_name} {self.user.last_name}"


class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name="Заказ")
    product = models.ForeignKey(to=Products, on_delete=models.SET_DEFAULT, null=True, verbose_name="Продукт", default=None)
    name = models.CharField(max_length=150, verbose_name="Название")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Цена")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Количество")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата продажи")




    class Meta:
        db_table = 'order_item'


    def products_price(self):
        return round(self.product.sell_price() * self.quantity, 2)

    def __str__(self):
        return f"Product {self.name} | Order № {self.order.pk}"

mysite/order/forms.py
import re

from django import forms

class CreateOrderForm(forms.Form):

    first_name = forms.CharField()
    last_name = forms.CharField()
    phone_number = forms.CharField()
    requires_delivery = forms.ChoiceField(
        choices=[
            ("0", False),
            ("1", True),
            ],
        )
    delivery_address = forms.CharField(required=False)
    payment_on_get = forms.ChoiceField(
        choices=[
            ("0", 'False'),
            ("1", 'True'),
            ],
        )

    def clean_phone_number(self):
        data = self.cleaned_data['phone_number']

        if not data.isdigit():
            raise forms.ValidationError("The phone number must contain only digits")

        pattern = re.compile(r'^\d{10}$')
        if not pattern.match(data):
            raise forms.ValidationError("Invalid phone number format")

        return data

mysite/order/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.db.models import Prefetch
from django.forms import ValidationError
from django.shortcuts import redirect, render

from cart.models import Cart
from django.utils.decorators import method_decorator
from django.views.generic import ListView, FormView

from .forms import CreateOrderForm
from .models import Order, OrderItem


from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db import transaction
from django.forms import ValidationError
from django.shortcuts import redirect, render

from cart.models import Cart

from .forms import CreateOrderForm
from .models import Order, OrderItem


@login_required
def create_order(request):
    if request.method == 'POST':
        form = CreateOrderForm(data=request.POST)
        if form.is_valid():
            try:
                with transaction.atomic():
                    user = request.user
                    cart_items = Cart.objects.filter(user=user)

                    if cart_items.exists():
                        order = Order.objects.create(
                            user=user,
                            phone_number=form.cleaned_data['phone_number'],
                            requires_delivery=form.cleaned_data['requires_delivery'],
                            delivery_address=form.cleaned_data['delivery_address'],
                            payment_on_get=form.cleaned_data['payment_on_get'],
                        )
                        for cart_item in cart_items:
                            product = cart_item.product
                            name = cart_item.product.name
                            price = cart_item.product.sell_price()
                            quantity = cart_item.quantity

                            if product.quantity < quantity:
                                raise ValidationError(f'Insufficient quantity of {name} in stock. Available - {product.quantity}')

                            OrderItem.objects.create(
                                order=order,
                                product=product,
                                name=name,
                                price=price,
                                quantity=quantity,
                            )
                            product.quantity -= quantity
                            product.save()

                        cart_items.delete()

                        messages.success(request, 'Order placed successfully!')
                        return redirect('users:profile')
            except ValidationError as e:
                messages.error(request, str(e))
                return redirect('cart:order')
    else:
        initial = {
            'first_name': request.user.first_name,
            'last_name': request.user.last_name,
        }
        form = CreateOrderForm(initial=initial)

    context = {
        'form': form,
        'orders': True,
    }
    return render(request, 'order/create_order.html', context=context)



@method_decorator(login_required, name='dispatch')
class OrderListView(ListView, LoginRequiredMixin):
    template_name = 'order/order-list.html'
    model = Order

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['orders'] = Order.objects.filter(user=self.request.user).prefetch_related(
            Prefetch(
                "orderitem_set",
                queryset=OrderItem.objects.select_related("product"),
            )
        ).order_by("-id")
        return context

mysite/order/templates/order/create_order.html
{% extends 'base.html' %}
{% load static %}
{% load carts_tags %}


{% block content %}
    <div class="bg-white p-4 mb-4 mx-2 rounded custom-shadow">
        <div class="container">
            <h3 class="text-center mb-4">Selected Products</h3>
            <div class="container" id="cart-items-container">
                <!-- Cart layout -->
                    {% user_carts request as carts %}

                    {% include 'cart/includes/include-cart.html' %}
                <!-- Cart layout ends -->
            </div>
        </div>
        <!-- Order details -->
        <div class="container">
            <h3 class="text-center">Order Details</h3>
            <div class="card mb-3">
                <div class="card-body">
                    <form action="{% url 'order:create_order' %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="id_first_name" class="form-label">First Name*:</label>
                                <input type="text" class="form-control" id="id_first_name"
                                       value="{% if form.first_name.value %} {{ form.first_name.value }} {% endif %}"
                                       name="first_name" required>
                                        {% if form.first_name.errors %}
                                            <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                                        {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_last_name" class="form-label">Last Name*:</label>
                                <input type="text" class="form-control" id="id_last_name"
                                       value="{% if form.last_name.value %} {{ form.last_name.value }} {% endif %}"
                                       name="last_name" required>
                                        {% if form.last_name.errors %}
                                            <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                                        {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_phone_number" class="form-label">Phone Number*:</label>
                                <input type="text" class="form-control" id="id_phone_number"
                                       value="{% if form.phone_number.value %} {{ form.phone_number.value }} {% endif %}"
                                       name="phone_number"
                                    placeholder="Format: XXX-XXX-XX-XX"
                                    required>
                                    {% if form.phone_number.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.phone_number.errors }}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="delivery" class="form-label">Delivery Method: </label>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="requires_delivery"
                                        id="id_requires_delivery" value="1" checked>
                                    <label class="form-check-label" for="id_requires_delivery">Delivery
                                        needed</label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="requires_delivery"
                                        id="id_requires_delivery" value="0">
                                    <label class="form-check-label" for="id_requires_delivery">Pickup</label>
                                </div>
                            </div>
                            <div class="mb-3" id="deliveryAddressField">
                                <label for="id_delivery_address" class="form-label">Delivery
                                    Address*:</label>
                                <textarea class="form-control" id="id_delivery_address"
                                          value="{% if form.delivery_address.value %} {{ form.delivery_address.value }} {% endif %}"
                                          name="delivery_address" rows="2"></textarea>
                                {% if form.delivery_address.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.delivery_address.errors }}</div>
                                {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label class="form-label">Payment Method: </label>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="payment_on_get"
                                        id="id_payment_on_get" value="0" checked>
                                    <label class="form-check-label" for="id_payment_on_get">Card Payment</label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="payment_on_get"
                                        id="id_payment_on_get" value="1">
                                    <label class="form-check-label" for="id_payment_on_get">Cash/Card
                                        on Delivery</label>
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-dark">Place Order</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mysite/order/templates/order/order-list.html
{% extends 'base.html' %}
{% load static %}
{% load carts_tags %}


{% block content %}
    <div class="col-md-12">
        <div class="bg-white p-4 mb-4 mx-2 rounded custom-shadow">
            <h3 class="text-center mb-4">My Orders</h3>
            <div class="container">
                <div class="accordion" id="accordionExample">
                    {% for order in orders %}
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="heading{{ order.id }}">
                            <button class="accordion-button {% if order != orders.0 %}collapsed{% endif %}" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ order.id }}" aria-expanded="false" aria-controls="collapse{{ order.id }}">
                                Order #{{ order.id }} - {{ order.created_at }} | Status: <strong class="mx-2">{{ order.requires_delivery }}</strong>
                            </button>
                        </h2>
                        <div id="collapse{{ order.id }}" class="accordion-collapse collapse {% if order == orders.0 %}show{% endif %}" aria-labelledby="heading{{ order.id }}" data-bs-parent="#accordionExample">
                            <div class="accordion-body">
                                <table class="table table-dark table-hover">
                                    <thead>
                                        <tr>
                                            <th>Product</th>
                                            <th>Quantity</th>
                                            <th>Price</th>
                                            <th>Total Price</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for item in order.orderitem_set.all %}
                                        <tr>
                                            <td><a class="text-white" href="{% url 'goods:product' item.product.id %}">{{ item.product.name }}</a></td>
                                            <td>{{ item.quantity }}</td>
                                            <td>{{ item.price }}</td>
                                            <td>{{ item.products_price }}</td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}