mysite/cart/urls.py
from django.urls import path

from .views import cart_add, cart_change, cart_remove

app_name = 'cart'

urlpatterns = [
    path('cart-add/', cart_add, name='cart_add'),
    path('cart-change/', cart_change, name='cart_change'),
    path('cart-remove/', cart_remove, name='cart_remove'),
]

mysite/goods/urls.py
from django.urls import path

from .views import (CategoryListView,
                    ProductDetailsView)
app_name = 'goods'

urlpatterns = [
    path('search/', CategoryListView.as_view(), name='search'),
    path('<slug:category_slug>/', CategoryListView.as_view(), name='index'),
    path('product/<int:pk>/', ProductDetailsView.as_view(), name='product')
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='goods')),
    path('user/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/order/urls.py
from django.urls import path
from .views import create_order, OrderListView

app_name = 'order'


urlpatterns = [
    path('create-order/', create_order, name='create_order'),
    path('order-list/', OrderListView.as_view(), name='order_list'),
]

mysite/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from .views import (login,
                    registration,
                    UserProfileView,
                    user_logout,
                    user_cart,
                    UserPasswordChangeView,
                    UserPasswordResetView,
                    UserPasswordResetDoneView,
                    UserPasswordResetConfirmView
                    )

app_name = 'users'


urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('user-cart/', user_cart, name='user-cart'),
    path('logout/', user_logout, name='logout'),
    path('password-change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('reset-password/', UserPasswordResetView.as_view(), name='password_reset'),
    path('reset-password-done/', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
]

mysite/order/models.py
from users.models import User
from django.db import models
from goods.models import Products

class OrderItemQueryset(models.QuerySet):
    def total_price(self):
        return sum(cart.products_price() for cart in self)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        else:
            return 0

class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, verbose_name="Пользователь", default=None)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания заказа")
    phone_number = models.CharField(max_length=20, verbose_name="Номер телефона")
    requires_delivery = models.BooleanField(default=False, verbose_name="Требуется доставка")
    delivery_address = models.TextField(null=True, blank=True, verbose_name="Адрес доставки")
    payment_on_get = models.BooleanField(default=False, verbose_name="Оплата при получении")
    is_paid = models.BooleanField(default=False, verbose_name="Оплачено")
    status = models.CharField(max_length=50, default='В обработке', verbose_name="Статус заказа")

    class Meta:
        db_table = 'order'

    def __str__(self):
        return f"Order № {self.pk} | Buyer {self.user.first_name} {self.user.last_name}"


class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name="Заказ")
    product = models.ForeignKey(to=Products, on_delete=models.SET_DEFAULT, null=True, verbose_name="Продукт", default=None)
    name = models.CharField(max_length=150, verbose_name="Название")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Цена")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Количество")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата продажи")




    class Meta:
        db_table = 'order_item'


    def products_price(self):
        return round(self.product.sell_price() * self.quantity, 2)

    def __str__(self):
        return f"Product {self.name} | Order № {self.order.pk}"

mysite/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):

    image = models.ImageField(upload_to='user_images', blank=True, null=True)
    phone_number = models.CharField(max_length=15, blank=True, null=True)

    class Meta:
        db_table = 'user'

mysite/users/forms.py
from django.contrib.auth.forms import (AuthenticationForm,
                                       UserCreationForm,
                                       UserChangeForm)
from django import forms

from .models import User


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']

    username = forms.CharField()
    password = forms.CharField()


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name',
                  'last_name',
                  'username',
                  'email',
                  'password1',
                  'password2')

    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()


class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = [
            'image',
            'first_name',
            'last_name',
            'username',
            'email'
        ]

    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()

mysite/users/views.py
from django.contrib import messages, auth
from django.contrib.auth import logout, get_user_model, authenticate, login as auth_login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (
    LoginView,
    PasswordChangeView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView
)
from django.db.models import Prefetch
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import FormView

from .forms import UserLoginForm, UserRegistrationForm, UserProfileForm
from cart.models import Cart
from order.models import Order, OrderItem


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)

            session_key = request.session.session_key

            if user:
                auth.login(request, user)
                messages.success(request, f"{username}, You are logged in")

                if session_key:
                    Cart.objects.filter(session_key=session_key).update(user=user)

                redirect_page = request.POST.get('next', None)
                if redirect_page and redirect_page != reverse('user:logout'):
                    return HttpResponseRedirect(request.POST.get('next'))

                return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserLoginForm()

    context = {
        'form': form
    }
    return render(request, 'users/login.html', context)


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()

            session_key = request.session.session_key

            user = form.instance
            auth.login(request, user)

            if session_key:
                Cart.objects.filter(session_key=session_key).update(user=user)
            messages.success(request, f"{user.username}, You have successfully registered and logged into your account")
            return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserRegistrationForm()

    context = {
        'form': form
    }
    return render(request, 'users/registration.html', context)


@method_decorator(login_required, name='dispatch')
class UserProfileView(FormView, LoginRequiredMixin):
    template_name = 'users/profile.html'
    form_class = UserProfileForm
    success_url = '/user/profile/'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['instance'] = self.request.user
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['orders'] = Order.objects.filter(user=self.request.user).prefetch_related(
            Prefetch(
                "orderitem_set",
                queryset=OrderItem.objects.select_related("product"),
            )
        ).order_by("-id")
        return context


def user_cart(request):
    return render(request, 'users/user-cart.html')

def user_logout(request):
    logout(request)
    messages.success(request, f'{request.user.username} You are logged out of your account.')
    return redirect(reverse('main:index'))



class UserPasswordChangeView(PasswordChangeView):
    template_name = 'users/password-change.html'
    success_url = reverse_lazy('users:profile')

    def form_valid(self, form):
        messages.success(self.request, f'{self.request.user.username} Your password has been changed successfully.')
        return super().form_valid(form)



class UserPasswordResetView(PasswordResetView):
    template_name = 'users/password-reset.html'
    success_url = reverse_lazy('users:password_reset_done')


class UserPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'users/password-reset-done.html'



class UserPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'users/password-reset-confirm.html'
    success_url = reverse_lazy('users:login')

mysite/users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="row mt-1">
            <div class="col-lg-2">
                <!-- Empty block at discretion -->
            </div>
            <div class="col-lg-10">
                <!-- Content on the page -->
                <div class="row">
                    <div class="container mt-5">
                        <div class="row justify-content-center">
                            <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                                <h2 class="text-center mb-4">Authorization</h2>

                                <form action="{% url 'users:login' %}" method="post">
                                    {% csrf_token %}
                                    {% if form.non_field_errors %}
                                        <div style="background-color: lavender; padding: 2px; border-radius: 8px;">
                                            <p> {{ form.non_field_errors }} </p>
                                        </div>
                                    {% endif %}
                                    <div class="mb-3">
                                        <label for="id_username" class="form-label">Username</label>
                                        <input type="text" class="form-control" id="id_username"
                                               name="username"
                                               placeholder="Enter your username"
                                               value="{% if form.username.value %} {{ form.username.value }} {% endif %}"
                                               required>
                                    </div>
                                    <div class="mb-3">
                                        <label for="id_password" class="form-label">Password</label>
                                        <input type="password" class="form-control" id="id_password" name="password" placeholder="Enter your password" required>
                                    </div>
                                    <button type="submit" class="btn btn-dark btn-block">Login</button>
                                </form>

                                <div class="mt-3">
                                    <a href="{% url 'users:password_reset' %}">Forgot your password?</a> | <a href="{% url 'users:registration' %}">Create an account</a>
                                </div>
                                <hr>
                                <div class="text-center">
                                    <p>Or sign in with:</p>
                                    <a href="#" class="btn btn-dark">
                                        <img class="mx-1" src="{% static '/deps/icons/google.svg' %}" alt="Google Icon" width="16" height="16">
                                        Google
                                    </a>
                                    <a href="#" class="btn btn-dark">
                                        <img class="mx-1" src="{% static '/deps/icons/facebook.svg' %}" alt="Facebook Icon" width="16" height="16">
                                        Facebook
                                    </a>
                                    <a href="#" class="btn btn-dark">
                                        <img class="mx-1" src="{% static '/deps/icons/github.svg' %}" alt="GitHub Icon" width="16" height="16">
                                        GitHub
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mysite/users/templates/users/password-reset-done.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="row mt-5 justify-content-center">
            <div class="col-md-80 bg-white p-5 rounded shadow-sm">
                <h2 class="text-center mb-4">Reset Password</h2>
                <p class="text-center mb-4">We have emailed you instructions to reset your password. Please check your email.</p>
                <hr>
                <div class="text-center">
                    <a href="{% url 'users:login' %}" class="btn btn-dark">Back to Login</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mysite/users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
{% load carts_tags %}

{% block content %}
    <div class="row">
        <div class="container mt-5">
            <div class="row">
                <!-- User profile data -->
                <div class="col-md-5">
                    <div class="bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                        <h3 class="text-center mb-4">User Profile</h3>

                        <form action="{% url 'users:profile' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-12 mb-3 text-center">
                                    {% if user.image %}
                                        <img src="{{ user.image.url }}"
                                         alt="User Avatar" class="img-fluid rounded-circle"
                                         style="max-width: 150px;">
                                    {% else %}
                                        <img src="{% static 'deps/images/baseavatar.jpg' %}"
                                             alt="User Avatar" class="img-fluid rounded-circle"
                                             style="max-width: 150px;">
                                    {% endif %}
                                    <input type="file" class="form-control mt-3" id="id_image"
                                        name="image"
                                        accept="image/*">
                                        {% if form.email.errors %}
                                            <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                                        {% endif %}
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_first_name" class="form-label">First Name*</label>
                                    <input type="text" class="form-control" id="id_first_name"
                                           placeholder="Enter your first name"
                                           name="first_name"
                                           value="{{ form.first_name.value }}" required>
                                           {% if form.first_name.errors %}
                                                <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                                           {% endif %}
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_last_name" class="form-label">Last Name*</label>
                                    <input type="text" class="form-control" id="id_last_name"
                                        placeholder="Enter your last name"
                                        name="last_name"
                                        value="{{ form.last_name.value }}" required>
                                        {% if form.last_name.errors %}
                                            <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                                        {% endif %}
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_username" class="form-label">Username*</label>
                                    <input type="text" class="form-control" id="id_username"
                                           placeholder="Enter your username"
                                           name="username"
                                           value="{{ form.username.value }}" required>
                                           {% if form.username.errors %}
                                                <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                                           {% endif %}
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_email" class="form-label">Email*</label>
                                    <input type="email" class="form-control" id="id_email"
                                           placeholder="Enter your email"
                                           name="email"
                                           value="{{ form.email.value }}" required>
                                           {% if form.email.errors %}
                                                <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                                           {% endif %}
                                </div>
                            </div>
                            <button type="submit" class="btn btn-dark">Save</button>
                            <a href="{% url 'users:password_change' %}" class="btn btn-dark">Change Password</a>
                        </form>

                    </div>
                </div>
                <!-- Cart -->
                <div class="col-md-7">
                    <div class="bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                        <h3 class="text-center mb-4">Basket</h3>
                        <div class="container" id="cart-items-container">
                            <!-- Cart markup -->
                            {% include 'cart/includes/include-cart.html' %}
                            <!-- End of cart markup -->
                        </div>
                        {% user_carts request as carts %}
                        {% if carts %}
                            <a class="btn btn-dark" href="{% url 'order:create_order' %}">
                                Place Order
                            </a>
                        {% endif %}
                    </div>
                </div>
                <!-- Completed orders -->
                <div class="col-md-12">
                    <div class="bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                        <h3 class="text-center mb-4">My Orders</h3>
                        <!-- Orders markup -->
                        <div class="container">
                            <div class="accordion" id="accordionExample">
                                {% for order in orders %}
                                <div class="accordion-item">
                                    <h2 class="accordion-header" id="heading{{ order.id }}">
                                        <button class="accordion-button {% if order != orders.0 %}collapsed{% endif %}" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ order.id }}" aria-expanded="false" aria-controls="collapse{{ order.id }}">
                                            Order #{{ order.id }} - {{ order.created_at }} | Status: <strong class="mx-2">{{ order.requires_delivery }}</strong>
                                        </button>
                                    </h2>
                                    <div id="collapse{{ order.id }}" class="accordion-collapse collapse {% if order == orders.0 %}show{% endif %}" aria-labelledby="heading{{ order.id }}" data-bs-parent="#accordionExample">
                                        <div class="accordion-body">
                                            <table class="table table-dark table-hover">
                                                <thead>
                                                    <tr>
                                                        <th>Product</th>
                                                        <th>Quantity</th>
                                                        <th>Price</th>
                                                        <th>Total Price</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    {% for item in order.orderitem_set.all %}
                                                    <tr>
                                                        <td><a class="text-white" href="{% url 'goods:product' item.product.id %}">{{ item.product.name }}</a></td>
                                                        <td>{{ item.quantity }}</td>
                                                        <td>{{ item.price }}</td>
                                                        <td>{{ item.products_price }}</td>
                                                    </tr>
                                                    {% endfor %}
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                        <!-- End of orders markup -->
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mysite/users/templates/users/registration.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="row mt-1">
            <div class="col-lg-2">
                <!-- Empty block at discretion -->
            </div>
            <div class="col-lg-10">
                <!-- Content on the page -->
                <div class="row">
                    <div class="container mt-5">
                        <div class="row justify-content-center">
                            <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                                <h2 class="text-center mb-4">Registration</h2>
                                <form action="{% url 'users:registration' %}" method="post">
                                    {% csrf_token %}

                                    <div class="row">
                                        <div class="col-md-6 mb-3">
                                            <label for="id_firstName" class="form-label">First Name*</label>
                                            <input type="text" class="form-control" name="first_name" id="id_firstName"
                                                    value="{% if form.first_name.value %} {{ form.first_name.value }} {% endif %}"
                                                    placeholder="Enter your first name" required>
                                                    {% if form.first_name.errors %}
                                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                                                    {% endif %}
                                        </div>
                                        <div class="col-md-6 mb-3">
                                            <label for="id_lastName" class="form-label">Last Name*</label>
                                            <input type="text" class="form-control" name="last_name" id="id_lastName"
                                                   value="{% if form.last_name.value %} {{ form.last_name.value }} {% endif %}"
                                                   placeholder="Enter your last name" required>
                                                    {% if form.last_name.errors %}
                                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                                                    {% endif %}
                                        </div>
                                        <div class="col-md-6 mb-3">
                                            <label for="id_username" class="form-label">Username*</label>
                                            <input type="text" class="form-control" name="username" id="id_username"
                                                   value="{% if form.username.value %} {{ form.username.value }} {% endif %}"
                                                   placeholder="Enter your username" required>
                                                    {% if form.username.errors %}
                                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                                                    {% endif %}
                                        </div>
                                        <div class="col-md-6 mb-3">
                                            <label for="id_email" class="form-label">Email*</label>
                                            <input type="email" class="form-control" name="email" id="id_email"
                                                   value="{% if form.email.value %} {{ form.email.value }} {% endif %}"
                                                   placeholder="Enter your email" required>
                                                    {% if form.email.errors %}
                                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                                                    {% endif %}
                                        </div>
                                        <div class="col-md-6 mb-3">
                                            <label for="id_password1" class="form-label">Password*</label>
                                            <input type="password" class="form-control" name="password1" id="id_password1"
                                                   value="{% if form.password1.value %} {{ form.password1.value }} {% endif %}"
                                                   placeholder="Enter password" required>
                                                    {% if form.password1.errors %}
                                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.password1.errors }}</div>
                                                    {% endif %}
                                        </div>
                                        <div class="col-md-6 mb-3">
                                            <label for="id_password2" class="form-label">Confirm Password*</label>
                                            <input type="password" class="form-control" name="password2" id="id_password2"
                                                   value="{% if form.password2.value %} {{ form.password2.value }} {% endif %}"
                                                   placeholder="Confirm password" required>
                                                    {% if form.password2.errors %}
                                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.password2.errors }}</div>
                                                    {% endif %}
                                        </div>
                                    </div>

                                    <button type="submit"
                                        class="btn btn-dark btn-block">Register</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}