mysite/cart/urls.py
from django.urls import path

from .views import cart_add, cart_change, cart_remove

app_name = 'cart'

urlpatterns = [
    path('cart-add/', cart_add, name='cart_add'),
    path('cart-change/', cart_change, name='cart_change'),
    path('cart-remove/', cart_remove, name='cart_remove'),
]

mysite/goods/urls.py
from django.urls import path

from .views import (CategoryListView,
                    ProductDetailsView)
app_name = 'goods'

urlpatterns = [
    path('search/', CategoryListView.as_view(), name='search'),
    path('<slug:category_slug>/', CategoryListView.as_view(), name='index'),
    path('product/<int:pk>/', ProductDetailsView.as_view(), name='product')
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='goods')),
    path('user/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/goods/models.py
from django.db import models


class Categories(models.Model):
    name = models.CharField(max_length=80, unique=True)
    slug = models.SlugField(max_length=150, unique=True, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'category'


class Products(models.Model):
    name = models.CharField(max_length=80, unique=True)
    slug = models.SlugField(max_length=150, unique=True, blank=True, null=True)
    description = models.TextField(max_length=500, blank=True, null=True)
    image = models.ImageField(upload_to='goods_images', blank=True, null=True)
    price = models.DecimalField(default=0.00, max_digits=8, decimal_places=2)
    discount = models.IntegerField(default=0)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(Categories, on_delete=models.CASCADE)

    def display_id(self) -> str:
        return f'{self.pk:05}'

    def sell_price(self):
        if self.discount:
            return round(self.price - self.price * self.discount / 100, 2)
        else:
            return self.price


    def __str__(self):
        return f'{self.name} -> {self.category}'

    class Meta:
        db_table = 'product'
        ordering = ['-id']

mysite/goods/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, get_list_or_404

from django.views.generic import ListView, DetailView
from .models import Products, Categories
from .utils import q_search


class CategoryListView(ListView):
    model = Products
    template_name = 'goods/category.html'
    context_object_name = 'goods'
    paginate_by = 3

    def get_queryset(self):
        on_sale = self.request.GET.get('on_sale', None)
        order_by = self.request.GET.get('order_by', None)
        query = self.request.GET.get('q', None)
        category_slug = self.kwargs.get('category_slug')

        queryset = super().get_queryset()

        if category_slug != 'all':
            queryset = queryset.filter(category__slug=category_slug)

        if query:
            queryset = q_search(query)

        if on_sale:
            queryset = queryset.filter(discount__gt=0)

        if order_by and order_by != 'default':
            queryset = queryset.order_by(order_by)

        return queryset


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_slug'] = self.kwargs.get('category_slug', None)
        return context


class ProductDetailsView(DetailView):
    template_name = 'goods/product.html'
    model = Products
    context_object_name = 'product'

mysite/goods/templates/goods/category.html
{% extends 'base.html' %}
{% load static %}
{% load goods_tags %}

{% block model_cart %}
    {% include 'includes/cart-button.html' %}
{% endblock %}

{% block content %}
    <div class="row">
        <!-- Filter form -->
        <div class="dropdown mb-2">
            <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                Filters
            </button>

            <form action="{% if request.GET.q %}{% url 'goods:search' %}{% else %}{% url 'goods:index' category_slug=category_slug %}{% endif %}" method="get" class="dropdown-menu bg-dark" data-bs-theme="dark">
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="checkbox" name="on_sale" id="flexCheckDefault" value="on"
                           {% if request.GET.on_sale == 'on' %} checked {% endif %}>
                    {% if request.GET.q %}
                        <input type="hidden" name="q" value="{{ request.GET.q }}">
                    {% endif %}
                    <label class="form-check-label" for="flexCheckDefault">
                        Products on Sale
                    </label>
                </div>
                <p class="text-white mx-3 mt-3">Sort by:</p>
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault1" value="default"
                    {% if not request.GET.order_by or request.GET.order_by == 'default' %} checked {% endif %}>
                    <label class="form-check-label" for="flexRadioDefault1">
                        Default
                    </label>
                </div>
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2" value="price"
                    {% if request.GET.order_by == 'price' %} checked {% endif %}>
                    <label class="form-check-label" for="flexRadioDefault2">
                        Price: Low to High
                    </label>
                </div>
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3" value="-price"
                    {% if request.GET.order_by == '-price' %} checked {% endif %}>
                    <label class="form-check-label" for="flexRadioDefault3">
                        Price: High to Low
                    </label>
                </div>
                <button type="submit" class="btn btn-primary mx-3 mt-3">Apply</button>
            </form>
        </div>
        <!-- Product cards -->
        {% for product in goods %}
            <div class="col-lg-4 col-md-6 p-4">
                <div class="card border-primary rounded custom-shadow">
                    {% if product.image %}
                        <img src="{{ product.image.url }}" class="card-img-top" alt="...">
                    {% endif %}
                    <div class="card-body">
                        <a href="{% url 'goods:product' pk=product.pk %}">
                            <p class="card-title">
                                {% autoescape off %}
                                {% if product.headline %}
                                {{ product.headline }}
                                {% else %}
                                {{ product.name }}
                                {% endif %}
                                {% endautoescape %}
                            </p>
                        </a>
                        <p class="card-text text-truncate">
                            {% autoescape off %}
                            {% if product.bodyline %}
                            {{ product.bodyline }}
                            {% else %}
                            {{ product.description }}
                            {% endif %}
                            {% endautoescape %}
                        </p>
                        <p class="product_id">id: {{ product.display_id }}</p>
                        <div class="d-flex justify-content-between">
                            {% if product.price %}
                                <p><s>{{ product.price }}</s> $</p>
                                <p><strong>{{ product.sell_price }} $</strong></p>
                                <span class="badge bg-warning text-dark">Discount: {{ product.discount }} %</span>
                            {% else %}
                                <p><strong>{{ product.price }} $</strong></p>
                            {% endif %}
                            <a href="{% url 'cart:cart_add' %}" class="btn add-to-cart"
                            data-product-id="{{ product.id }}">
                                {% csrf_token %}
                                <img class="mx-1" src="{% static 'deps/icons/cart-plus.svg' %}" alt="Catalog Icon"
                                    width="32" height="32">
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <!-- Pagination -->
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center my-4">
            <div class="custom-shadow d-flex">
                <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                  <a class="page-link" href="{% if page_obj.has_previous %}
                    ?{% change_params page=page_obj.previous_page_number %}
                  {% else %} # {% endif %}">Previous</a>
                </li>
                {% for page in page_obj.paginator.page_range %}
                {% if page >= page_obj.number|add:-2 and page <= page_obj.number|add:2 %}
                    <li class="page-item {% if page_obj.number == page %} active {% endif %}">
                        <a class="page-link" href="?{% change_params page=page %}">{{ page }}</a>
                    </li>
                {% endif %}
                {% endfor %}
                <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                  <a class="page-link" href="{% if page_obj.has_next %}
                        ?{% change_params page=page_obj.next_page_number %}
                    {% else %} # {% endif %}">Next</a>
                </li>
            </div>
        </ul>
    </nav>
{% endblock %}

mysite/goods/templates/goods/product.html
{% extends 'base.html' %}
{% load static %}'

{% block model_cart %}
    {% include 'includes/cart-button.html' %}
{% endblock %}

{% block content %}
    <div class="container mt-5">
        <div class="card mb-4 custom-shadow">
            <div class="row">
                <!-- Миниатюры -->
                <div class="col-md-4">
                    <img src="{{ product.image.url }}"
                        class="img-thumbnail" data-bs-toggle="modal" data-bs-target="#imageModal1">
                </div>
                <div class="col-md-4 ">
                    <p class="product_id mt-3">id: {{ product.display_id }}</p>
                </div>
                <!-- Увеличить изображение в модальном окне -->
                <div class="modal fade" id="imageModal1" tabindex="-1"
                    aria-labelledby="imageModal1Label" aria-hidden="true">
                    <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="imageModal1Label">Изображение 1</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Закрыть"></button>
                            </div>
                            <div class="modal-body">
                                <img src="{{ product.image.url }}"
                                    class="img-fluid" alt="Изображение 1">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Описание товара -->
            <div class="card-body">
                <p class="card-text">Price: <strong> {{ product.sell_price }} $</strong></p>
                <h5 class="card-title">{{ product.name }}</h5>
                <p class="card-text">{{ product.description }}</p>
                <a href="{% url 'cart:cart_add' %}" class="btn btn-dark add-to-cart"
                data-product-id="{{ product.id }}">
                    {% csrf_token %}
                    Add to Basket</a>
            </div>
        </div>
    </div>
{% endblock %}